---
plugin: amazon.aws.aws_ec2
regions:
  - us-east-2
filters:
  tag:Project: ansible-aws-lab
  instance-state-name: running
hostnames:
  - tag:Name
  - private_ip_address
compose:
  ansible_host: public_ip_address
keyed_groups:
  - key: tags.Role
    prefix: ""
    separator: ""
  - key: tags.Environment
    prefix: ""
    separator: ""
  - key: instance_type
    prefix: type
    separator: "_"
